language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10'
  - '9'
  - '8'
script:
  - npm run test-ci
  - npm run build-ci
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
before_deploy:
  - git add .
  - git commit --message "Travis build: $TRAVIS_BUILD_NUMBER"
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  - git push && git push --tags
deploy:
  provider: npm
  email: rkabrahpudi@taxilla.com
  api_key: $NPM_TOKEN
  on:
    tags: false
